Update installation scripts.
optimumBA/phx.tools pull request #16
Opened 2024-08-12 21:30 UTC by amos-kibet

https://3.basecamp.com/5023736/buckets/38393000/todos/7680613475

2024-08-13 21:12 UTC, amos-kibet commented
@almirsarajcic, I am yet to fix the failing issues on CI (they do not fail locally), but would love a review for the parts that do not necessarily depend on CI passing.

2024-09-05 18:34 UTC, almirsarajcic requested changes

2024-09-05 18:34 UTC, almirsarajcic commented on .mise.toml
> +_.file = '.env.sample'
That's a sample file. During onboarding, you're supposed to copy its contents into a `.env` file, as we do in all our projects. Please revert.

2024-09-05 18:34 UTC, almirsarajcic commented on .tool-versions
> +elixir 1.17.2-otp-27
If you're going to change the versions in this place, you need to do the same in CI, Dockerfile and everywhere else they are referenced. Either revert or fix the version in these other places too.

2024-09-05 18:34 UTC, almirsarajcic commented on priv/static/macOS.sh
> +# possible shells (cat /etc/shells)
I guess it's still WIP.

2024-09-05 18:34 UTC, almirsarajcic commented on priv/static/macOS.sh
> +    "xcode")
It's not the whole Xcode that we're installing here.

2024-09-18 23:27 UTC, almirsarajcic approved these changes

2024-09-18 23:29 UTC, merged